AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "bin/rails"
    - "bin/spring"
    - "bin/bundle"
    - "bin/rake"
  DisplayCopNames: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - "spec/**/*"

# Prefer compact style
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

Style/GuardClause:
  MinBodyLength: 5
Style/ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/HashSyntax:
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/PerlBackrefs:
  AutoCorrect: false

Style/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  Exclude:
    - "spec/**/*"

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceAroundOperators:
  AllowForAlignment:
    - "="
    - "=>"
    - "||"

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/*.rb"
