version: '2.1'
services:
  web: &app_base
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - UID=${UID-1000}
        - APP_HOME=${PWD}
        - SKIP_BUNDLE=yes
    ports:
     - "3333:3333"
    command: rails s -p 3333 -b 0.0.0.0
    stdin_open: true
    tty: true
    links:
     - db
    volumes:
      - bundle:/usr/local/bundle
      - .:${PWD}
    environment: &env_base
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:@db:5432
      ENCRYPTION_KEY: abcdefghijklmn
      GITHUB_ORGANIZATION: 'degica'
      GITHUB_DEVELOPER_TEAM: 'developers'
      GITHUB_ADMIN_TEAM: 'Admin developers'
  worker:
    <<: *app_base
    ports: []
    command: rake jobs:work
  spring:
    <<: *app_base
    ports: []
    command: spring server
    pid: host
    volumes:
      - bundle:/usr/local/bundle
      - .:${PWD}
  db:
    image: postgres:9.5
    environment:
      PGDATA: /data
    volumes:
      - pgdata:/data
volumes:
  pgdata:
  bundle:
