version: '2'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - APP_HOME=${PWD}
    ports:
     - "3333:3333"
    command: rails s -p 3333 -b 0.0.0.0
    stdin_open: true
    tty: true
    links:
     - db
    volumes:
      - .:${PWD}
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:@db:5432
  worker:
    <<: *app_base
    ports: []
    command: rake jobs:work
  spring:
    <<: *app_base
    ports: []
    command: spring server
    pid: host
    environment:
      DATABASE_URL: postgres://postgres:@db:5432
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:${PWD}
      - spring:/tmp/spring
  db:
    image: postgres:9.5
volumes:
  spring:
